# Base Certify configuration — generated by institution-kit. Do not edit by hand.
spring.application.name=certify
spring.cloud.config.enabled=false
spring.cloud.config.uri=

server.port=8090
server.servlet.path=/v1/certify

openapi.info.title=Certify Service
openapi.info.description=Rest Endpoints for operations related to certify
openapi.info.version=1.0
openapi.info.license.name=Mosip
openapi.info.license.url=https://docs.mosip.io/platform/license
mosip.certify.domain.url=${CERTIFY_PUBLIC_URL}
mosipbox.public.url=${CERTIFY_PUBLIC_URL}
openapi.service.server.url=${mosip.certify.domain.url}${server.servlet.path}
openapi.service.server.description=Certify Service
springdoc.swagger-ui.disable-swagger-default-url=true
spring.mvc.servlet.path=${server.servlet.path}

spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.main.allow-bean-definition-overriding=true
spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER

mosip.certify.data-provider-plugin.did-url=${DID_URL}
mosip.certify.data-provider-plugin.issuer.key-manager-app-id=CERTIFY_VC_SIGN_ED25519
mosip.certify.data-provider-plugin.issuer.key-manager-ref-id=ED25519_SIGN

## -------------------------------------- Authentication & Authorization -----------------------------------------------
mosip.certify.security.auth.post-urls={}
mosip.certify.security.auth.put-urls={}
mosip.certify.security.auth.get-urls={}

# Paths are relative to server.servlet.path (/v1/certify). Use leading "/" so
# Spring Security 6 MvcRequestMatcher matches (**/actuator/** does not).
mosip.certify.security.ignore-csrf-urls=/actuator/**,/favicon.ico,/error,\
  /swagger-ui/**,/v3/api-docs/**,\
  /issuance/**,/credential-configurations/**,/.well-known/**,/ledger-search/**,/credentials/**,\
  /oauth/**,/pre-authorized-data/**,/credential-offer-data/**

mosip.certify.security.ignore-auth-urls=/actuator/**,/error,/swagger-ui/**,\
  /v3/api-docs/**,/issuance/**,/rendering-template/**,/system-info/**,/credential-configurations/**,\
  /.well-known/**,/ledger-search/**,/credentials/**,/oauth/**,/pre-authorized-data/**,/credential-offer-data/**

mosip.certify.security.cors-enabled-get-method-urls=/rendering-template/**

## ------------------------------------------ Discovery / OID4VCI -------------------------------------------
mosip.certify.discovery.issuer-id=${mosip.certify.domain.url}${server.servlet.path}
mosip.certify.authorization.url=https://cuenta.digital.gob.do
mosip.certify.plugin-mode=DataProvider
mosip.certify.supported.jwt-proof-alg={'RS256','PS256','ES256','Ed25519'}
mosip.certify.cnonce-expire-seconds=40

mosip.certify.identifier=${mosip.certify.domain.url}
mosip.certify.authn.filter-urls={ '${server.servlet.path}/issuance/credential', '${server.servlet.path}/issuance/vd11/credential', '${server.servlet.path}/issuance/vd12/credential' }
mosip.certify.authn.issuer-uri=https://cuenta.digital.gob.do
mosip.certify.authn.jwk-set-uri=https://cuenta.digital.gob.do/.well-known/jwks.json
mosip.certify.authn.allowed-audiences={ '${mosipbox.public.url}${server.servlet.path}/issuance/credential', '${mosip.certify.authorization.url}/v1/esignet/vci/credential' }

# CuentaDigital / RD MVP — validaciones relajadas (ver docs/IUGO-CUSTOMIZATIONS.md)
mosip.certify.authn.validate-audience=false
mosip.certify.authn.require-client-id-claim=false
mosip.certify.issuance.validate-cnonce=false

## ---------------------------------------- Actuator --------------------------------------------------------
management.endpoint.env.show-values=ALWAYS
management.endpoints.web.exposure.include=*
management.health.redis.enabled=false

#------------------------------------ Key-manager --------------------------------------------------
mosip.kernel.crypto.asymmetric-algorithm-name=RSA/ECB/OAEPWITHSHA-256ANDMGF1PADDING
mosip.kernel.crypto.symmetric-algorithm-name=AES/GCM/NoPadding
mosip.kernel.keygenerator.asymmetric-algorithm-name=RSA
mosip.kernel.keygenerator.symmetric-algorithm-name=AES
mosip.kernel.keygenerator.asymmetric-key-length=2048
mosip.kernel.keygenerator.symmetric-key-length=256
mosip.kernel.data-key-splitter=#KEY_SPLITTER#
mosip.kernel.crypto.gcm-tag-length=128
mosip.kernel.crypto.hash-algorithm-name=PBKDF2WithHmacSHA512
mosip.kernel.crypto.hash-symmetric-key-length=256
mosip.kernel.crypto.hash-iteration=100000
mosip.kernel.crypto.sign-algorithm-name=RS256
mosip.kernel.certificate.sign.algorithm=SHA256withRSA

mosip.kernel.keymanager.hsm.config-path=CERTIFY_PKCS12/local.p12
mosip.kernel.keymanager.hsm.keystore-type=PKCS12
mosip.kernel.keymanager.hsm.keystore-pass=local

mosip.kernel.keymanager.certificate.default.common-name=www.example.com
mosip.kernel.keymanager.certificate.default.organizational-unit=EXAMPLE-CENTER
mosip.kernel.keymanager.certificate.default.organization=IIITB
mosip.kernel.keymanager.certificate.default.location=BANGALORE
mosip.kernel.keymanager.certificate.default.state=KA
mosip.kernel.keymanager.certificate.default.country=IN

mosip.kernel.keymanager.softhsm.certificate.common-name=www.example.com
mosip.kernel.keymanager.softhsm.certificate.organizational-unit=Example Unit
mosip.kernel.keymanager.softhsm.certificate.organization=IIITB
mosip.kernel.keymanager.softhsm.certificate.country=IN

mosip.kernel.partner.sign.masterkey.application.id=PMS
mosip.kernel.partner.allowed.domains=DEVICE
mosip.kernel.keymanager-service-validate-url=https://${mosip.hostname}/keymanager/validate
mosip.kernel.keymanager.jwtsign.validate.json=false
mosip.keymanager.dao.enabled=false
crypto.PrependThumbprint.enable=true

mosip.kernel.keymgr.hsm.health.check.enabled=true
mosip.kernel.keymgr.hsm.health.key.app-id=CERTIFY_SERVICE
mosip.kernel.keymgr.hsm.healthkey.ref-id=TRANSACTION_CACHE
mosip.kernel.keymgr.hsm.health.check.encrypt=true
mosip.certify.cache.security.secretkey.reference-id=TRANSACTION_CACHE

##----------------------------------------- Database --------------------------------------------------------
mosip.certify.database.hostname=database
mosip.certify.database.port=5432
spring.datasource.url=jdbc:postgresql://database:5432/${POSTGRES_DB}?currentSchema=certify
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

## ---------------------------------------- Cache --------------------------------------------------------
spring.cache.type=simple
spring.cache.cache-names=${mosip.certify.cache.names}
mosip.certify.access-token-expire-seconds=86400
mosip.certify.templatecache-expire-seconds=1800
mosip.certify.certificatedatacache-expire-seconds=3600
mosip.certify.common.cache-expire-seconds=3600
mosip.certify.jwks-cache-expire-seconds=300
mosip.certify.cache.names=userinfo,vcissuance,templatecache,credentialConfig,certificatedatacache,renderTemplate,jwks,issuerMetadataCache
mosip.certify.cache.size={'userinfo': 200, 'vcissuance': 2000, 'jwks': 1}
mosip.certify.cache.expire-in-seconds={'userinfo': ${mosip.certify.access-token-expire-seconds}, 'vcissuance': ${mosip.certify.access-token-expire-seconds}, 'certificatedatacache': ${mosip.certify.certificatedatacache-expire-seconds}, 'credentialConfig': ${mosip.certify.common.cache-expire-seconds}, 'renderTemplate': ${mosip.certify.common.cache-expire-seconds}, 'jwks': ${mosip.certify.jwks-cache-expire-seconds}, 'templatecache': ${mosip.certify.templatecache-expire-seconds}}

mosip.certify.credential-config.cryptographic-binding-methods-supported={\
  'ldp_vc': {'did:jwk','did:web'},\
  'mso_mdoc': {'cose_key'},\
  'vc+sd-jwt': {'did:jwk','did:web'}\
}
mosip.certify.credential-config.credential-signing-alg-values-supported={\
  'RsaSignature2018': {'RS256'},\
  'Ed25519Signature2018': {'EdDSA'},\
  'Ed25519Signature2020': {'EdDSA'},\
  'EcdsaKoblitzSignature2016': {'ES256K'},\
  'EcdsaSecp256k1Signature2019': {'ES256K'},\
  'EcdsaSecp256r1Signature2019': {'ES256'},\
  'ecdsa-rdfc-2019': {'ES256'},\
  'ecdsa-jcs-2019': {'ES256'},\
  'eddsa-rdfc-2022': {'EdDSA'},\
  'eddsa-jcs-2022': {'EdDSA'}\
}
mosip.certify.credential-config.proof-types-supported={\
  'jwt': {'proof_signing_alg_values_supported': {'RS256', 'PS256', 'ES256', 'EdDSA'}}\
}

mosip.certify.status-list.signature-crypto-suite=Ed25519Signature2020
mosip.certify.status-list.signature-algo=EdDSA
mosip.certify.statuslist.size-in-kb=16
mosip.certify.data-provider-plugin.credential-status.supported-purposes={'revocation'}
mosip.certify.data-provider-plugin.credential-status.allowed-status-purposes={'revocation'}
mosip.certify.issuer.ledger-enabled=true
mosip.certify.signature-algo.key-alias-mapper={\
    'RS256': {{'CERTIFY_VC_SIGN_RSA', ''}},\
    'EdDSA': {{'CERTIFY_VC_SIGN_ED25519', 'ED25519_SIGN'}},\
    'ES256K': {{'CERTIFY_VC_SIGN_EC_K1', 'EC_SECP256K1_SIGN'}},\
    'ES256': {{'CERTIFY_VC_SIGN_EC_R1', 'EC_SECP256R1_SIGN'}}\
}
mosip.certify.credential-config.issuer.display={\
  {\
    'name': '${INSTITUTION_DISPLAY_NAME}',\
    'locale': 'es'\
  }\
}
mosip.certify.indexed-mappings.national_id=$.national_id

mosip.certify.integration.scan-base-package=io.mosip.certify.restapidataprovider.integration
mosip.certify.integration.audit-plugin=LoggerAuditService
mosip.certify.integration.data-provider-plugin=RestApiDataProviderPlugin

## ------------------------------------------- OAuth AS metadata (unused AS; required at startup) -------------------------------------------
mosip.certify.oauth.issuer=${mosip.certify.authorization.url}
mosip.certify.oauth.token-endpoint=${mosip.certify.authorization.url}${server.servlet.path}/oauth/token
mosip.certify.oauth.jwks-uri=${mosip.certify.authorization.url}${server.servlet.path}/.well-known/jwks.json
mosip.certify.oauth.grant-types-supported=authorization_code,urn:ietf:params:oauth:grant-type:pre-authorized_code
mosip.certify.oauth.response-types-supported=code
mosip.certify.oauth.code-challenge-methods-supported=S256
mosip.certify.oauth.interactive-authorization-endpoint=${mosip.certify.authorization.url}${server.servlet.path}/oauth/iar
mosip.certify.oauth.access-token.audience=${mosip.certify.identifier}${server.servlet.path}/issuance/credential
mosip.certify.authorization.default-server=${mosip.certify.oauth.issuer}
mosip.certify.credential-config.as-mapping={}
mosip.certify.credential-offer-url=${mosip.certify.domain.url}${server.servlet.path}/credential-offer-data/
mosip.certify.pre-auth-code.default-expiry-seconds=600
mosip.certify.pre-auth-code.min-expiry-seconds=60
mosip.certify.pre-auth-code.max-expiry-seconds=3600
