# Institution-specific Certify configuration — generated by institution-kit. Do not edit by hand.
mosip.certify.integration.scan-base-package=io.mosip.certify.mock.integration,io.mosip.certify.restapidataprovider.integration
mosip.certify.integration.vci-plugin=RestApiDataProviderPlugin
mosip.certify.integration.data-provider-plugin=RestApiDataProviderPlugin
mosip.certify.plugin-mode=DataProvider

mosip.certify.data-provider-plugin.restapi.base-url=${RESTAPI_BASE_URL}
mosip.certify.data-provider-plugin.restapi.auth-token=
mosip.certify.data-provider-plugin.id-field-prefix-uri=https://mosip.io/credential/
mosip.certify.data-provider-plugin.issuer.vc-sign-algo=Ed25519Signature2020
mosip.certify.data-provider-plugin.restapi.scope-endpoint-mapping=${RESTAPI_SCOPE_ENDPOINT_MAPPING}

mosip.certify.data-provider-plugin.restapi.auth.token-url=https://cuenta.digital.gob.do/oauth2/token
mosip.certify.data-provider-plugin.restapi.auth.client-id=${OAUTH_CLIENT_ID}
mosip.certify.data-provider-plugin.restapi.auth.client-secret=${OAUTH_CLIENT_SECRET}

mosip.certify.database.name=${POSTGRES_DB}
mosip.certify.mock.vciplugin.verification-method=${mosip.certify.authn.jwk-set-uri}
mosip.certify.cache.security.algorithm-name=AES/ECB/PKCS5Padding
mosip.certify.cache.secure.individual-id=false
mosip.certify.cache.store.individual-id=true
